services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870 # UI
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=sdg-cluster
    env_file:
      - ./config
    networks:
      - sdg_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HDFS_DATANODE_HOSTNAME: datanode
    env_file:
      - ./config
    networks:
      - sdg_network

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  sdg_network:
    name: sdg_network
    external: true
